name: "Conventional Commits"
description: "Ensures that all commit messages are following the conventional-commits standard."
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: false
  VALID_LABELS:
    description: 'The default conventional commit categories'
    required: false
    default: '["feat","fix","docs","style","refactor","test","build","perf","ci","chore","revert","merge","wip"]'
runs:
  using: node16
  main: dist/index.js
